### ISSUE TITLE
Publish on crates for Naga-0.5

### ISSUE THREAD

**Issue by kvark** [Kangz/glslpp-rs#44]
We are doing the Naga-0.5 publishing, and it would be good to include GLSL with this preprocessor.

**Comment by Kangz** [comment]
I prepped a [tag](https://github.com/Kangz/glslpp-rs/releases/tag/0.2) and will publish it on crates.io as soon as Github Actions starts working again.

**Comment by kvark** [comment]
You should at least restart the action periodically. It's not going to kick in automatically.

**Comment by Kangz** [comment]
Yep, I was AFK and it needed one more fix in #45. v0.2.1 is now published.
