### ISSUE TITLE
Support for #line

### ISSUE THREAD

**Issue by Kangz** [Kangz/glslpp-rs#5]
This is pretty useful when concatenating source together.

**Comment by Kangz** [comment]
This is still missing support for expression in #line, but also the "file" part of #line (TBD if it is a string or a number or either?)

**Comment by JCapucho** [comment]
The expression parsing is fixed with #31, the file part is currently parsed and evaluated but it's ignored and I think this is dependent in #16 so I'm closing this issue (also glsl only allows numbers as valid file sources)
